question_data = [
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "All program codes have to be compiled into an executable file in order to be run. "
                 "This file can then be executed on any machine.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "There are 86400 seconds in a day.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "question": "Type 1 diabetes is a result of the liver working improperly.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "Donkey Kong was originally set to be a Popeye arcade game.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Sports", "type": "boolean", "difficulty": "medium",
     "question": "Tennis was once known as Racquetball.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "easy",
     "question": "Bill Cipher in the show &quot;Gravity Falls&quot; is the good guy.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "History", "type": "boolean", "difficulty": "easy",
     "question": "United States President John F. Kennedy was assassinated during his"
                 " presidential motorcade in Atlanta, Georgia on November 22nd, 1963.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The term &quot;Spam&quot; came before the food product &quot;Spam&quot;.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "The alternative rock band, They Might Be Giants, released their "
                 "album &#039;Flood&#039; in 1990. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In the game Dead by Daylight, the killer Michael Myers is referred to as &quot;The Shape&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In Terraria, you can craft the Cell Phone pre-hardmode.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Politics", "type": "boolean", "difficulty": "medium",
     "question": "George W. Bush lost the popular vote in the 2004 "
                 "United States presidential election.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Sports", "type": "boolean", "difficulty": "easy",
     "question": "In association football, or soccer, a corner kick is when the game restarts"
                 " after someone scores a goal.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "History", "type": "boolean", "difficulty": "hard",
     "question": "The USS Missouri (BB-63) last served in the Korean War.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "Kiznaiver is an adaptation of a manga.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "hard",
     "question": "The board game Go has more possible legal positions than the number of atoms in the "
                 "visible universe.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium", "question": "Sugar contains fat.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In &quot;Call Of Duty: World At War&quot;, the first appearance of the &quot;PPSH-41&quot; "
                 "in &quot;Zombies&quot; was in the map &quot;Der Riese&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
     "question": "In the &quot;To Love-Ru&quot; series, Peke is considered a female robot.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The game &quot;Pocket Morty&quot; has a Morty called &quot;Pocket Morty's Morty&quot;?",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "The character that would eventually become Dr. Eggman was considered for the role of Sega&#039;s"
                 " new flagship mascot before Sonic was.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "question": "Pneumonoultramicroscopicsilicovolcanoconiosis is a synonym for the disease known as silicosis.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
     "question": "In the &quot;Kagerou Daze&quot; series, Shintaro Kisaragi is prominently shown with the color red.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In &quot;Need for Speed: Porsche Unleashed&quot;, the player can only drive cars "
                 "manufactured by Porsche.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
     "question": "Sir Issac Newton served as a Member of Parliament, but the only recorded time he spoke was "
                 "to complain about a draft in the chambers.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "A pasodoble is a type of Italian pasta sauce.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "medium",
     "question": "In &quot;Avatar: The Last Airbender&quot; and &quot;The Legend of Korra&quot;, Lavabending "
                 "is a specialized bending technique of Firebending.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy", "question": "Rabbits are carnivores.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In &quot;Space Station 13&quot;,  the station has a clown aboard it.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
]
